import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Button from './components/buttons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#f0efef] ${inter.className} h-screen max-h-screen`}>
        <header className="bg-[#32cd32] p-2 py-3 h-20">
          <h1>Logo</h1>
        </header>
        {children}
        <footer className='p-3 h-16 mt-2'>
          <Button>
            Salir
          </Button>
        </footer>
      </body>
    </html>
  )
}
